version: "3"
services:
  wikidb:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /home/bhsoft/internal_services/wiki/data:/var/lib/postgresql/data
    ports:
      - "8640:5432"
  wiki:
    container_name: wiki-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - wikidb
    ports:
      - "8636:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki